// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: exp1

#include "ui.h"
#include "arduino.h"
void btn1_click(lv_event_t * e)
{
	// Your code here
	Serial.println("clicked\r\n");
}
