// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: exp1

#include "../ui.h"


// COMPONENT btn1

lv_obj_t * ui_btn1_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_btn1;
    cui_btn1 = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_btn1, 100);
    lv_obj_set_height(cui_btn1, 50);
    lv_obj_set_align(cui_btn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_btn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_btn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BTN1_NUM);
    children[UI_COMP_BTN1_BTN1] = cui_btn1;
    lv_obj_add_event_cb(cui_btn1, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_btn1, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_btn1_create_hook(cui_btn1);
    return cui_btn1;
}

